const data = {
  products: [
    {
      name: 'F-15 eagle',
      slug: 'f-15',
      category: 'usa',
      image: '/images/1.jpg',
      price: 120000000,
      countInStock: 10,
      brand: 'lochid martin',
      rating: 4.5,
      numReviews: 10,
      description: 'multi roll fighter',
    },
    {
      name: 'F_22 Raptor',
      slug: 'f_22',
      category: 'usa',
      image: '/images/2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'lochid martin',
      rating: 4.0,
      numReviews: 10,
      description: 'the best in the world !',
    },
    {
      name: 'F-35 lightining',
      slug: 'f-35',
      category: 'lochid martin',
      image: '/images/3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'lochid martin',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Su-57 Pacfa',
      slug: 'su-57',
      category: 'Pants',
      image: '/images/4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
